### ISSUE TITLE
Make column header fully clickable

### ISSUE THREAD

**Issue by vdestraitt** [ToucanToco/vue-query-builder#301]
Today to open the operations menu of a column, we need to precisely click on the 'v' chevron that appears on the right of the column header.

We should rather make the header fully clickable, i.e. we can open the operations menu of a column even when clicking on the column name for example.

**Comment by adimascio** [comment]
just a small warning: this might conflict at some point with a possible click-to-sort asc / top operation.

**Comment by Dalanir** [comment]
For the moment, I suggest to always display the caret to show that we can click on it in order to access options, what do you think @vdestraitt @adimasci ?

**Comment by zegonz** [comment]
seems that we can close this issue @Dalanir ?
