### ISSUE TITLE
Step creation (+ edition) form

### ISSUE THREAD

**Issue by adimascio** [ToucanToco/vue-query-builder#33]
Each step is created (or edited) via a specific form.

We have yet to decide if these forms are built manually or with something like https://github.com/fagbokforlaget/vue-jsonschema-form

**Comment by vdestraitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ETQC j'ai un Visual Query Builder v1](https://trello.com/c/HdU5IPmL/3202-etqc-jai-un-visual-query-builder-v1)

**Comment by vdestraitt** [comment]
For the MVP we chose to build the forms manually (using json schema for vaidation).
We may decide to use a form builder inn further iterations
