### ISSUE TITLE
Toy backend for easier testing

### ISSUE THREAD

**Issue by adimascio** [ToucanToco/vue-query-builder#34]
As a developer, it would be nice to test the editor in real conditions with real data (e.g. CSV files or a toy mongo database).

One could imagime something like:

```bash
git clone https://github.com/ToucanToco/vue-query-builder/issues/new
python examples/toy-backend.py my-config-file.yml
yarn start-demo
```

**Comment by piotch** [comment]
yo @adimascio we could maybe do this using node rather than python ? It avoids having two lang and al. to install 

- https://www.npmjs.com/package/mongodb-memory-server
- https://www.npmjs.com/package/csv

If you agree with this approach, happy to try to do something.

**Comment by adimascio** [comment]
> yo @adimascio we could maybe do this using node rather than python ? It avoids having two lang and al. to install

Hey @piotch. Indeed, we could definitely go with a pure JS approach to avoid mixing languages and package managers.
