### ISSUE TITLE
Replace value with another

### ISSUE THREAD

**Issue by adimascio** [ToucanToco/vue-query-builder#40]
As a query designer, I can click on a column and choose the "replace value" transformation step. The step creation form is displayed and I'm asked to select values (either by manually entering values or by clicking on a cell) and choose the corresponding replacement value.

This will generate a `ReplaceStep` in the pipeline.

**Comment by vdestraitt** [comment]
Same as #61 and #78

**Comment by adimascio** [comment]
The postprocess translation will be implemented in v2 as well as the `click-on-cell` interaction
