### ISSUE TITLE
Filter by value

### ISSUE THREAD

**Issue by adimascio** [ToucanToco/vue-query-builder#41]
As a query designer, I can click on a column, click on the "filter" step and pick the value to filter on either by clicking on a cell or manually entering the value.

This will generate a `FilterStep` in the pipeline

**Comment by vdestraitt** [comment]
Translation to mongo: #63 
Translation to mongo: #81

**Comment by adimascio** [comment]
The postprocess translation will be implemented in v2, probably as well as the `click-on-cell` interaction.
