### ISSUE TITLE
Handle simple translation of aggregation step → mongo 3.6

### ISSUE THREAD

**Issue by adimascio** [ToucanToco/vue-query-builder#57]
Implement the aggregation step translation described in https://github.com/ToucanToco/vue-query-builder/issues/30 with the following restrictions:

- no postprocess, mongo 3.x only,
- handle aggregation functions that have direct mongo 3.x mapping (i.e. no `count_distinct`)

**Comment by vdestraitt** [comment]
@adimascio can we close this issue following PR #58 ?
